### ISSUE TITLE
bug: Kitty doesn't change font size back when close zenmode

### ISSUE THREAD

**Issue by devbyP** [folke/zen-mode.nvim#87]
### Did you check docs and existing issues?

- [X] I have read all the zen-mode.nvim docs
- [X] I have searched the existing issues of zen-mode.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Manjaro Linux 22.0.4 Sikaris

### Describe the bug

This Kitty font-size plugins work perfectly fine on my Mac. However, on my linux machine,
font size remain changed after open zenmode and does not change back when close zenmode.

the Kitty config is mostly default (just change theme and font_family).

I've already set required options.
`allow_remote_control socket_only`
`listen_on unix:/tmp/kitty`

Both my mac and linux have the same setting and have same version of neovim: 0.8.3

my mac kitty version: 0.26.5
Manjaro kitty version: 0.27.1

From the information above, I not sure this have to do with the OS or kitty version, or both.

my setting:

``` lua
require("twilight").setup()
local zen = require("zen-mode")
zen.setup({
    plugins = {
        kitty = {
            enabled = true,
            font = "+6",
        },
    },
    on_open = function()
        vim.cmd.colorscheme("spaceduck")
    end,
    on_close = function()
        vim.cmd.colorscheme("rose-pine")
    end,
})

vim.keymap.set('n', '<leader>z', zen.toggle, { silent = true })
```

### Steps To Reproduce

I've tried delete `on_open` and `on_close` function, but doesn't work.
I also try change  value of `font`.
When changed font to number
``` lua
kitty = {
    enabled = true,
    font = "20",
}
```
font size will remain 20 after close.

if change font size to `+` or `-` number
``` lua
kitty = {
    enabled = true,
    font = "+6",
}
```
font size will keep changing every time I open zenmode.

### Expected Behavior

Font size go back to the size in kitty config file when close zenmode.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/zen-mode.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by devbyP** [comment]
I found that the command `kitty @ --to $KITTY_LISTEN_ON set-font-size "0"`
Which kitty function called when disabled zenmode, is not working on the newer version of kitty.
Seem like cannot use "0" as a value anymore.

the error when call the command:
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 682, in _execute_remote_command
    response = handle_cmd(self, window, pcmd, peer_id, self_window)
  File "/usr/bin/../lib/kitty/kitty/remote_control.py", line 220, in handle_cmd
    ans = c.response_from_kitty(boss, self_window or window, PayloadGetter(c, payload))
  File "/usr/bin/../lib/kitty/kitty/rc/set_font_size.py", line 46, in response_from_kitty
    boss.change_font_size(
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1164, in change_font_size
    new_size = calc_new_size(current_size)
  File "/usr/bin/../lib/kitty/kitty/boss.py", line 1145, in calc_new_size
    new_size = max(MINIMUM_FONT_SIZE, min(new_size, get_options().font_size * 5))
TypeError: '<' not supported between instances of 'float' and 'NoneType'

Error: '<' not supported between instances of 'float' and 'NoneType'
```
